<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Skenario_2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e6ccfb14-9fc7-4ae3-aaf6-f185521ed631</testSuiteGuid>
   <testCaseLink>
      <guid>077c6583-1b59-411a-bc3f-1058b2ea3c2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Skenario_2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eae1569c-3558-4afb-aaf2-42e564984518</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>eae1569c-3558-4afb-aaf2-42e564984518</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>e66e1dee-1cbe-419b-bfbd-8296c24e24af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eae1569c-3558-4afb-aaf2-42e564984518</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0e973fdd-f2f4-4b9a-a5ca-e4798bbf5f6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fd4d9a8-34ce-4cd3-b501-f8cd5be00f69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>841c061c-792c-478b-b39b-7db65c8710d5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
