<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Skenario_7</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ca962cd7-9e11-4554-ae69-ec990197484e</testSuiteGuid>
   <testCaseLink>
      <guid>077c6583-1b59-411a-bc3f-1058b2ea3c2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Skenario_7</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eae1569c-3558-4afb-aaf2-42e564984518</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>eae1569c-3558-4afb-aaf2-42e564984518</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>bfc57225-9221-4a8e-a0e7-99fac462018a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eae1569c-3558-4afb-aaf2-42e564984518</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>b4c54650-2509-434f-a32b-a5919e289f44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c89620-b690-49d3-afcb-5149df3e78a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa0872e-669f-413b-98c8-b2f5892f3e5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
